version: '2'
services:
    loadbalancer:
        image: containous/traefik
        restart: always
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - ./traefik.toml:/etc/traefik/traefik.toml
            - /var/run/docker.sock:/var/run/docker.sock
    worker:
        image: seqvence/worker:latest
        restart: always
        depends_on:
            - webserver
        entrypoint: python /opt/worker/worker.py
    webserver:
        image: seqvence/webserver:latest
        ports:
            - "8000"
        labels:
            - "traefik.backend=gunicorn"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.frontend.rule=Host"
            - "traefik.frontend.value=dockerize.it"
        entrypoint: /usr/bin/supervisord -c /etc/supervisord.conf --nodaemon


