version: '2'
services:
    webserver:
        image: webserver:latest
        ports:
            - "5000:5000"
        links:
            - mongodb
        depends_on:
            - mongodb
        entrypoint: python /opt/webserver/webservice.py
        volumes:
            - /Users/al3x/code/seqvence/docker-bday/docker-bday-backend:/opt/webserver
            - /Users/al3x/code/seqvence/docker-bday/docker-bday-frontend/resources/public:/opt/webserver/static
    mongodb:
        image: mongo:latest
