version: '2'
services:
    worker:
        image: worker:latest
        links:
            - mongodb
        depends_on:
            - webserver
        entrypoint: python /opt/worker/worker.py
    webserver:
        image: webserver:latest
        ports:
            - "5000:5000"
        links:
            - mongodb
        depends_on:
            - mongodb
        entrypoint: python /opt/webserver/webservice.py
    mongodb:
        image: mongo:latest
