---
- hosts: localhost
  connection: local
  sudo: yes
  vars:
      internal_ip: "{{ INTERNAL_IP }}"
      consul_endpoint: "{{ CONSUL_ENDPOINT }}"
      hostname: "slave0"
  roles:
      - {role: "/root/ansible/docker",
         docker_opts: "--cluster-store=consul://{{ consul_endpoint }}:8500 --cluster-advertise={{ internal_ip }}:2375 -H tcp://{{ internal_ip  }}:2375 -H unix:///var/run/docker.sock"}
      - {role: "/root/ansible/slave"}
