---
- hosts: localhost
  connection: local
  sudo: yes
  vars:
      internal_ip: "{{ INTERNAL_IP }}"
      consul_servers_string: "{{ CONSUL_ENDPOINT }}"
      hostname: "{{ HOSTNAME }}"
      consul_client_ip: "172.17.0.1"
  roles:
      - {role: "/root/ansible/ansible-consul",
         consul_version: 0.6.3,
         consul_servers: ["{{ consul_servers_string }}"],
         consul_join_at_start: true,
         consul_retry_join: true,
         consul_bind_address: "{{ internal_ip }}",
         consul_client_address: "{{ consul_client_ip }}",
         consul_client_address_bind: true,
         consul_encrypt: "UjE0uJ9EorI4rMQL4gtFWw==",
         consul_node_name: "{{ hostname }}"}
      - {role: "/root/ansible/docker",
         docker_opts: "--cluster-store=consul://{{ consul_client_ip }}:8500 --cluster-advertise={{ internal_ip }}:2375 -H tcp://{{ internal_ip  }}:2375 -H unix:///var/run/docker.sock"}
      - {role: "/root/ansible/slave"}
